import { GANTT_STAGE_STYLES } from '../resources/META-INF/resources/static/assets/js/utils/result-presentation.mjs';
import validateSchema from 'mcp-view-validator';
import { createViewerBridge, readEnvelope } from './bridge.mjs';
import { parsePlanTime, formatPlanTime, poiPosition } from './model.mjs';
import { translate, supportedLocale } from './i18n.mjs';
import { colorFor } from './palette.mjs';

const $ = (id) => document.getElementById(id);
const record = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);

export function startViewer({ kind, buildModel, validateSemantics, buildReplay, mapApi }) {
  const mapMode = kind === 'map';
  const state = {
    envelope:null, model:null, replay:null, input:null, expectedJob:null, boundVersion:null,
    engineerId:null, ticketId:null, missingEngineer:null, locale:'zh-CN', theme:'light', mode:'inline',
    sidebar:'agents', search:'', sidebarOpen:false, zoom:1, scroll:{left:0,top:0}, cursor:null,
    speed:1, playing:false, follow:false, connected:false, refreshing:false, error:null, stale:false, destroyed:false,
    map:null, mapKey:null, mapReady:false, mapError:null, mapEpoch:0, frame:0, lastTick:null,
    messageBusy:false, intentText:'', inputApplied:false,
  };
  const t = (key) => translate(state.locale, key);
  const node = (tag, text, className) => { const el=document.createElement(tag); if(text!==undefined)el.textContent=String(text); if(className)el.className=className; return el; };
  const button = (text, click, className) => { const el=node('button',text,className);el.type='button';el.addEventListener('click',click);return el; };
  const label = (value) => value === null || value === undefined || value === '' ? t('none') : String(value);
  const nameOf = (agent) => agent ? agent.name || agent.id : t('unknown');
  const optional = (id, action) => { const el=$(id); if(el)action(el); return el; };
  const pair = (box,key,value) => box.append(node('dt',t(key)),node('dd',label(value),'result-detail-value'));
  const selectedAgent = () => state.model?.indexes.agents.get(state.engineerId);
  const selectedTicket = () => state.model?.indexes.tickets.get(state.ticketId);

  function errorKey(error) {
    const code=error?.code||'';
    if(/AUTH|TOKEN|UNAUTHENTICATED/.test(code))return 'auth';
    if(/FORBIDDEN|ACCESS_DENIED|NOT_FOUND/.test(code))return 'denied';
    if(/TOOL_MISMATCH/.test(code))return 'wrongTool';
    if(/RESOURCE/.test(code))return 'resource';
    if(/VIEW_UNSUPPORTED/.test(code))return 'unsupportedView';
    if(/FULLSCREEN/.test(code))return 'fullscreenDenied';
    if(/CANCEL/.test(code))return 'canceledTool';
    if(/UNAVAILABLE/.test(code))return 'unavailable';
    if(/TOOL_FAILED|RATE_LIMITED|REQUEST_SCHEMA/.test(code))return 'businessError';
    if(/REFRESH_FAILED|CONNECTION_CLOSED|NOT_CONNECTED/.test(code))return 'networkError';
    if(/MODEL|ENVELOPE|IDENTITY|CONTRACT|SCHEMA|INPUT/.test(code))return 'invalidResult';
    return 'protocolError';
  }
  function tell(key,{stale=false}={}){state.error=key;state.stale=stale;renderNotice();}
  function renderNotice(){const el=$('notice');if(!el)return;el.hidden=!state.error&&!state.refreshing;el.dataset.error=String(Boolean(state.error));el.textContent=state.refreshing?t('refreshing'):state.error?`${state.stale?t('stale')+' · ':''}${t(state.error)}`:'';}
  function pause(){state.playing=false;state.lastTick=null;cancelAnimationFrame(state.frame);state.frame=0;optional('play',el=>{el.textContent=t('play');el.setAttribute('aria-pressed','false');});}
  function disposeMap(){state.mapEpoch++;state.map?.dispose();state.map=null;state.mapKey=null;state.mapReady=false;state.mapError=null;}
  function clearData(){pause();disposeMap();state.envelope=null;state.model=null;state.replay=null;state.cursor=null;state.engineerId=null;state.ticketId=null;state.missingEngineer=null;state.search='';optional('search',el=>{el.value='';});}
  function resetSelection(){state.engineerId=null;state.ticketId=null;state.missingEngineer=null;state.cursor=null;state.zoom=1;state.scroll={left:0,top:0};state.search='';optional('search',el=>{el.value='';});}
  function handleError(error){if(state.destroyed)return;pause();if(error?.clearData){clearData();state.expectedJob=null;}tell(errorKey(error),{stale:!error?.clearData&&Boolean(state.envelope)&&!/FULLSCREEN/.test(error?.code||'')});render();}
  function acceptInput(input){if(state.destroyed)return;if(input.job_id!==state.expectedJob){clearData();resetSelection();state.expectedJob=input.job_id;state.inputApplied=false;state.error=null;}state.input=input;render();}
  function acceptResult(result,meta){
    if(state.destroyed||meta?.requestJobId&&state.expectedJob&&meta.requestJobId!==state.expectedJob)return;
    try{
      const envelope=readEnvelope(result,{viewKind:kind,expectedJobId:state.expectedJob||undefined,expectedVersionId:state.boundVersion||undefined,expectedToolName:bridge.getHostContext()?.toolInfo?.tool?.name,validateView:(value)=>validateSchema(value)&&validateSemantics(value)});
      const model=envelope.engine_view?buildModel(envelope.engine_view):null;
      if(model?.invalidIdentity)throw Object.assign(new Error('invalid'),{code:'MCP_UI_MODEL_INVALID',clearData:true});
      const changed=state.envelope?.job_id!==envelope.job_id;pause();if(changed){disposeMap();resetSelection();}
      state.envelope=envelope;state.model=model;state.replay=model&&buildReplay?buildReplay(model):null;state.expectedJob=envelope.job_id;state.boundVersion=envelope.image_version_id;state.error=null;state.stale=false;
      if(!state.inputApplied){state.engineerId=mapMode?envelope.engineer_id:null;state.inputApplied=true;}
      if(state.engineerId&&!model?.indexes.agents.has(state.engineerId)){state.missingEngineer=state.engineerId;state.engineerId=null;tell('engineerNotFound');}
      if(state.ticketId&&!model?.indexes.tickets.has(state.ticketId))state.ticketId=null;
      render();if(mapMode)void syncMap({refresh:true});
    }catch(error){handleError(error);}
  }
  function hostContext(context){
    if(state.destroyed)return;const oldMode=state.mode,oldLocale=state.locale;
    state.locale=supportedLocale(context.locale);state.theme=context.theme==='dark'?'dark':'light';state.mode=context.displayMode==='fullscreen'?'fullscreen':'inline';
    if(oldMode==='fullscreen'&&state.mode!=='fullscreen')pause();
    document.documentElement.lang=state.locale;document.documentElement.dataset.theme=state.theme;
    const colors={'--color-background-primary':'--surface','--color-background-secondary':'--surface-alt','--color-text-primary':'--ink','--color-text-secondary':'--muted','--color-border-primary':'--line'};
    for(const [host,local]of Object.entries(colors)){const value=context.styles?.variables?.[host];if(typeof value==='string'&&CSS.supports('color',value))document.documentElement.style.setProperty(local,value);else document.documentElement.style.removeProperty(local);}
    render();if(mapMode){if(oldLocale!==state.locale)void syncMap({refresh:true,reload:true});else state.map?.resize();}
  }
  const bridge=createViewerBridge({onInput:acceptInput,onResult:acceptResult,onHostContext:hostContext,onError:handleError,onTeardown:cleanup},{viewKind:kind});

  function localize(){
    const labels={refresh:'refresh',fullscreen:state.mode==='fullscreen'?'exitFullscreen':'fullscreen','engineer-label':'engineer','sidebar-toggle':'objects','fit-map':'fit','side-agents':'agents','side-tickets':'tickets','search-label':'search','map-retry':'retryMap','playback-label':'playback',follow:'follow','speed-label':'speed','footer':'footer','gantt-title':'ganttTitle','gantt-in':'zoomIn','gantt-out':'zoomOut','open-gantt':'viewGantt','copy-intent':'copyIntent'};
    for(const [id,key]of Object.entries(labels))optional(id,el=>{el.textContent=t(key);});
    optional('search',el=>{el.placeholder=t('search');});
    optional('map-canvas',el=>el.setAttribute('aria-label',t('mapLabel')));optional('gantt-scroll',el=>el.setAttribute('aria-label',t('chartLabel')));
  }
  function renderEngineerSelect(){const el=$('engineer');if(!el)return;const options=[new Option(state.missingEngineer?`${state.missingEngineer} · ${t('missingReference')}`:t('allEngineers'),'')];for(const agent of state.model?.agents||[])options.push(new Option(`${nameOf(agent)}${agent.date?' · '+agent.date:''}`,agent.id));el.replaceChildren(...options);el.value=state.engineerId||'';el.disabled=!state.model?.agents||state.missingEngineer!=null;}
  function ticketOrder(ticket){const owner=state.model?.indexes.agents.get(ticket.agent),index=owner?.tickets?.indexOf(ticket.id);return Number.isInteger(index)&&index>=0?index+1:null;}
  function selectEngineer(id){pause();state.missingEngineer=null;state.engineerId=id||null;state.ticketId=null;state.cursor=null;state.error=null;render();if(mapMode){void syncMap({refresh:true});state.map?.fit();}}
  function selectTicket(id,ownerId=null){const ticket=state.model?.indexes.tickets.get(id);if(!ticket)return;state.ticketId=id;const agent=state.model.indexes.agents.get(ownerId||ticket.agent);if(agent&&agent.virtual!==true)state.engineerId=agent.id;pause();state.cursor=null;render();if(mapMode){void syncMap({refresh:true});state.map?.focus(poiPosition(state.model.indexes.pois.get(ticket.loc)));}}
  function swatch(id){const el=node('span',undefined,'swatch');el.style.setProperty('--agent-color',colorFor(id));el.setAttribute('aria-hidden','true');return el;}
  function ticketRow(id,index,ownerId){const ticket=state.model?.indexes.tickets.get(id),poi=ticket&&state.model.indexes.pois.get(ticket.loc);const row=button('',()=>selectTicket(id,ownerId),'ticket-row');row.dataset.focusKey=`ticket:${ownerId||''}:${id}`;row.setAttribute('aria-pressed',String(state.ticketId===id));row.append(node('span',index===null?'—':index+1,'number'));const copy=node('span',undefined,'row-copy');copy.append(node('span',id),node('small',ticket?`${poi?.name||t('none')} · ${label(ticket.start_service_time)} → ${label(ticket.departure_time)}`:t('missingReference')));row.append(copy);return row;}
  function renderDetails(box){if(!box)return;box.replaceChildren();const ticket=selectedTicket(),agent=selectedAgent();if(!ticket&&!agent){box.append(node('p',t('choose'),'muted'));return;}box.append(node('h2',ticket?.id||nameOf(agent),'detail-heading'));const dl=node('dl',undefined,'detail-grid');if(ticket){const poi=state.model.indexes.pois.get(ticket.loc),owner=state.model.indexes.agents.get(ticket.agent);pair(dl,'owner',ticket.agent===null?t('unassigned'):owner?nameOf(owner):t('missingReference'));pair(dl,'sequence',ticketOrder(ticket));pair(dl,'arrival',ticket.arrival_time);pair(dl,'start',ticket.start_service_time);pair(dl,'departure',ticket.departure_time);pair(dl,'location',poi?.name||(ticket.loc?t('missingReference'):null));pair(dl,'address',poi?.address);}else{pair(dl,'id',agent.id);pair(dl,'date',agent.date);pair(dl,'shift',agent.shift_start_time);pair(dl,'assigned',agent.tickets?.length??null);}box.append(dl);}
  function renderSidebar(){const box=$('sidebar');if(!box)return;const narrow=innerWidth<=700;box.hidden=state.mode!=='fullscreen'||(narrow&&!state.sidebarOpen);optional('sidebar-toggle',el=>{el.hidden=state.mode!=='fullscreen'||!narrow;el.setAttribute('aria-expanded',String(state.sidebarOpen));});for(const key of ['agents','tickets'])optional(`side-${key}`,el=>{el.setAttribute('aria-selected',String(state.sidebar===key));el.tabIndex=state.sidebar===key?0:-1;});const list=$('side-list');list.replaceChildren();const query=state.search.toLocaleLowerCase();if(!state.model){list.append(node('p',t('noResult'),'empty'));renderDetails($('side-detail'));return;}const values=state.sidebar==='agents'?state.model.agents:state.model.tickets;if(values===null){list.append(node('p',t('unknownCollections'),'empty'));return;}if(state.sidebar==='agents'){for(const agent of values||[]){if(query&&!`${agent.id} ${agent.name||''}`.toLocaleLowerCase().includes(query))continue;const row=button('',()=>selectEngineer(agent.id),'ticket-row');row.setAttribute('aria-pressed',String(agent.id===state.engineerId));row.append(swatch(agent.id));const copy=node('span',undefined,'row-copy');copy.append(node('span',nameOf(agent)),node('small',`${label(agent.date)} · ${t('tickets')} ${agent.tickets?.length??t('unknown')}`));row.append(copy);list.append(row);}}else for(const ticket of values||[]){if(state.engineerId&&ticket.agent!==state.engineerId)continue;const poi=state.model.indexes.pois.get(ticket.loc);if(query&&!`${ticket.id} ${poi?.name||''}`.toLocaleLowerCase().includes(query))continue;const order=ticketOrder(ticket);list.append(ticketRow(ticket.id,order===null?null:order-1,ticket.agent));}if(!list.childNodes.length)list.append(node('p',t(query?'noMatch':'empty'),'empty'));renderDetails($('side-detail'));}

  function ganttAgents(){return(state.model?.agents||[]).filter((agent)=>!state.engineerId||agent.id===state.engineerId);}
  function renderGantt(){
    const chart=$('gantt-chart'),scroll=$('gantt-scroll');if(!chart||!scroll)return;const legend=$('gantt-legend');legend.replaceChildren();
    for(const [type,key]of[['travel','travel'],['wait','waitingPhase'],['service','service']]){const item=node('span',undefined,'result-phase-key'),dot=node('span',undefined,'result-phase-dot');dot.style.cssText=GANTT_STAGE_STYLES[type].dot;dot.setAttribute('aria-hidden','true');item.append(dot,node('span',t(key)));legend.append(item);}
    chart.replaceChildren();if(!state.model){chart.append(node('p',state.envelope?t('noResult'):t('waiting'),'empty'));return;}const agents=ganttAgents(),times=[];
    for(const agent of agents){const shift=parsePlanTime(agent.shift_start_time);if(shift!==null&&agent.tickets?.length)times.push(shift);for(const id of agent.tickets||[]){const ticket=state.model.indexes.tickets.get(id);if(ticket)for(const key of['arrival_time','start_service_time','departure_time']){const value=parsePlanTime(ticket[key]);if(value!==null)times.push(value);}}}
    if(!times.length){chart.append(node('p',t('noSchedule'),'empty'));return;}const min=Math.min(...times),max=Math.max(...times),span=max-min,grid=node('div',undefined,'gantt-grid');grid.style.width=`${Math.max(640,scroll.clientWidth)*state.zoom}px`;const head=node('div',undefined,'gantt-head');head.append(node('div',t('engineer'),'gantt-label'));const scale=node('div',undefined,'gantt-scale');for(let i=0;i<5;i++){const tick=node('span',formatPlanTime(min+span*i/4).slice(5),'gantt-tick');tick.style.left=`${i*25}%`;scale.append(tick);}head.append(scale);grid.append(head);const percent=(time)=>span===0?50:Math.max(0,Math.min(100,100*(time-min)/span));
    for(const agent of agents){const row=node('div',undefined,'gantt-row'),caption=node('div',undefined,'gantt-label'),choose=button('',()=>selectEngineer(agent.id));choose.append(swatch(agent.id),node('span',nameOf(agent)));caption.append(choose,node('small',`${agent.date?.slice(5)||'—'} · ${label(agent.shift_start_time?.slice(11,16))}`));row.append(caption);const track=node('div',undefined,'gantt-track');let previous=parsePlanTime(agent.shift_start_time);
      for(const [index,id]of(agent.tickets||[]).entries()){const ticket=state.model.indexes.tickets.get(id);if(!ticket)continue;const arrival=parsePlanTime(ticket.arrival_time),start=parsePlanTime(ticket.start_service_time),end=parsePlanTime(ticket.departure_time);if(arrival===null||start===null||end===null||start<arrival||end<start)continue;const stages=[];if(previous!==null&&arrival>previous)stages.push(['travel',previous,arrival]);if(start>arrival)stages.push(['wait',arrival,start]);stages.push(['service',start,end]);const first=Math.min(...stages.map(x=>x[1])),last=Math.max(...stages.map(x=>x[2])),duration=last-first,group=node('div',undefined,'gantt-visit result-timeline-bar');group.style.left=`${percent(first)}%`;group.style.width=`${Math.max(0,percent(last)-percent(first))}%`;group.dataset.selected=String(state.ticketId===ticket.id);for(const [phase,a,b]of stages){const style=GANTT_STAGE_STYLES[phase],bar=button('',()=>selectTicket(ticket.id,agent.id),'gantt-bar');bar.style.setProperty('--stage-fill',style.background);bar.style.setProperty('--stage-ink',style.text);bar.style.left=`${duration===0?0:100*(a-first)/duration}%`;bar.style.width=`${duration===0?0:100*(b-a)/duration}%`;bar.dataset.phase=phase==='wait'?'waiting':phase;bar.dataset.zero=String(a===b);bar.setAttribute('aria-label',`${index+1} · ${ticket.id} · ${t(phase==='wait'?'waitingPhase':phase)} · ${formatPlanTime(a)} → ${formatPlanTime(b)}`);group.append(bar);}const badge=node('span',undefined,'gantt-visit-label');badge.append(node('span',index+1,'result-sequence-badge'));group.append(badge);track.append(group);previous=end;}
      if(Array.isArray(agent.tickets)&&!agent.tickets.length)track.append(node('span',t('noTickets'),'gantt-missing'));row.append(track);grid.append(row);}
    chart.append(grid);scroll.scrollLeft=state.scroll.left;scroll.scrollTop=state.scroll.top;
  }
  function renderLegend(scene){const box=$('map-legend');if(!box)return;box.replaceChildren();for(const agent of(state.model?.agents||[]).filter(a=>a.virtual!==true&&(!state.engineerId||state.engineerId===a.id))){const el=button('',()=>selectEngineer(agent.id));el.append(swatch(agent.id),node('span',nameOf(agent)));el.setAttribute('aria-pressed',String(state.engineerId===agent.id));box.append(el);}if(scene?.warnings.length)box.append(node('span',scene.warnings.map(t).join(' · '),'map-warning'));}
  function mapMessage(){if(!state.envelope)return t(state.error==='noHost'?'noHost':'waiting');if(!state.model)return`${t(state.envelope.result_state)} · ${t('noResult')}`;const keys={MAP_DISABLED:'mapDisabled',MAP_PROVIDER_MISMATCH:'mapMismatch',MAP_CONFIG:'mapConfig',MAP_NO_POINTS:'mapNoPoints',MAP_CSP_BLOCKED:'mapBlocked',MAP_LOAD_FAILED:'mapFailed',MAP_TIMEOUT:'mapTimeout',MAP_RESIZE_FAILED:'mapResizeFailed'};return state.mapError?t(keys[state.mapError]||'mapFailed'):t('mapLoading');}
  function renderMapStatus(){optional('map-state',el=>{el.hidden=state.mapReady;});optional('map-message',el=>{el.textContent=mapMessage();});optional('map-retry',el=>{el.hidden=!state.model||!state.mapError;});optional('fit-map',el=>{el.disabled=!state.mapReady;});}
  async function syncMap({refresh=false,reload=false}={}){if(!mapMode||state.destroyed)return;if(!state.model||state.missingEngineer){disposeMap();renderMapStatus();return;}const scene=mapApi.buildMapScene(state.model,{agentId:state.engineerId,ticketId:state.ticketId});renderLegend(scene);const context=state.envelope.map_context,key=JSON.stringify([context,state.envelope.job_id,state.locale]);if(state.map&&state.mapKey===key&&!reload){if(refresh&&state.mapReady)state.map.update(scene);renderMapStatus();updatePlayback();return;}const viewport=state.map?.getViewport();disposeMap();state.mapKey=key;const epoch=state.mapEpoch;renderMapStatus();const map=new mapApi.MapView($('map-canvas'),{onSelect:(item)=>item.kind==='agent'?selectEngineer(item.id):selectTicket(item.id),onFailure:(error)=>{if(epoch!==state.mapEpoch)return;state.mapError=error.code;state.mapReady=false;map.dispose();pause();renderMapStatus();updatePlayback();}});state.map=map;try{await map.mount(context,state.envelope.task.map_provider,scene,state.locale,state.envelope.image_version_id);if(state.destroyed||epoch!==state.mapEpoch){map.dispose();return;}state.mapReady=true;map.update(scene);if(viewport)map.setViewport(viewport);}catch(error){if(epoch===state.mapEpoch){state.mapError=error.code||'MAP_LOAD_FAILED';state.mapReady=false;map.dispose();}}renderMapStatus();updatePlayback();}
  function replayRange(){const agents=(state.model?.analysis?.engineers||[]).filter(a=>a.replay_eligible&&(!state.engineerId||a.id===state.engineerId));return!agents.length?{start:null,end:null,ids:[]}:{start:Math.min(...agents.map(a=>parsePlanTime(a.replay_start))),end:Math.max(...agents.map(a=>parsePlanTime(a.replay_end))),ids:agents.map(a=>a.id)};}
  function updatePlayback(){if(!mapMode)return;const range=replayRange();optional('playback',el=>{el.hidden=state.mode!=='fullscreen';});const playable=range.start!==null&&state.mapReady,canFollow=playable&&Boolean(state.engineerId)&&range.ids.includes(state.engineerId);optional('playback-scope',el=>{el.textContent=t(playable?'eligible':'notPlayable');});optional('play',el=>{el.textContent=t(state.playing?'pause':'play');el.disabled=!playable||range.end===range.start;el.setAttribute('aria-pressed',String(state.playing));});optional('follow',el=>{if(!canFollow)state.follow=false;el.disabled=!canFollow;el.setAttribute('aria-pressed',String(state.follow));});if(range.start===null){optional('playback-time',el=>{el.textContent='—';});return;}state.cursor=Math.max(range.start,Math.min(range.end,state.cursor??range.start));optional('cursor',el=>{el.disabled=!playable;el.value=range.end===range.start?'0':String(Math.round((state.cursor-range.start)/(range.end-range.start)*1000));el.setAttribute('aria-valuetext',formatPlanTime(state.cursor));});optional('playback-time',el=>{el.textContent=formatPlanTime(state.cursor);});if(state.mode==='fullscreen'&&state.mapReady){const positions=state.replay.at(state.cursor,range.ids);state.map.moveAgents(positions);if(state.follow){const focus=positions.find(item=>item.id===state.engineerId);state.map.focus(focus?.position);}}}
  function playbackFrame(now){if(!state.playing||state.destroyed)return;const range=replayRange();if(range.start===null||!state.mapReady){pause();return;}if(state.lastTick!==null)state.cursor=Math.min(range.end,(state.cursor??range.start)+(now-state.lastTick)*state.speed);state.lastTick=now;updatePlayback();if(state.cursor>=range.end){pause();return;}state.frame=requestAnimationFrame(playbackFrame);}
  function togglePlay(){if(state.playing){pause();updatePlayback();return;}const range=replayRange();if(!state.mapReady||range.start===null||state.mode!=='fullscreen')return;if(state.cursor>=range.end)state.cursor=range.start;state.playing=true;state.lastTick=null;state.frame=requestAnimationFrame(playbackFrame);updatePlayback();}
  function renderIntent(){const box=$('intent-status');if(!box)return;box.hidden=!state.intentText;optional('intent-text',el=>{el.value=state.intentText;});}
  async function openGantt(){if(!mapMode||!state.envelope||state.messageBusy)return;state.messageBusy=true;optional('open-gantt',el=>{el.disabled=true;el.textContent=t('sendingGantt');});const result=await bridge.sendGanttIntent(state.envelope);state.messageBusy=false;state.intentText=result.sent?'':result.text;tell(result.sent?'ganttSent':'ganttUnknown');render();}
  function render(){if(state.destroyed)return;localize();$('app').dataset.mode=state.mode;$('app').setAttribute('aria-busy',String(!state.envelope&&!state.error));optional('refresh',el=>{el.disabled=!state.connected||!state.envelope||state.refreshing;});optional('fullscreen',el=>{const modes=bridge.getHostContext()?.availableDisplayModes||[];el.disabled=!state.connected||(!modes.includes('fullscreen')&&state.mode!=='fullscreen');});renderNotice();renderEngineerSelect();renderSidebar();if(mapMode){renderMapStatus();updatePlayback();renderIntent();}else{renderGantt();renderDetails($('inline-detail'));}}

  optional('engineer',el=>el.addEventListener('change',(event)=>selectEngineer(event.target.value)));
  optional('refresh',el=>el.addEventListener('click',async()=>{if(!state.envelope||state.refreshing)return;pause();state.refreshing=true;render();try{await bridge.refresh(state.envelope,{engineerId:mapMode?state.engineerId:undefined});}finally{state.refreshing=false;render();}}));
  optional('fullscreen',el=>el.addEventListener('click',()=>bridge.requestDisplayMode(state.mode==='fullscreen'?'inline':'fullscreen')));
  optional('fit-map',el=>el.addEventListener('click',()=>state.map?.fit()));optional('map-retry',el=>el.addEventListener('click',()=>syncMap({reload:true})));optional('open-gantt',el=>el.addEventListener('click',openGantt));
  optional('copy-intent',el=>el.addEventListener('click',async()=>{const input=$('intent-text');input?.select();try{await navigator.clipboard.writeText(state.intentText);tell('copied');}catch{document.execCommand?.('copy');}}));
  optional('gantt-scroll',el=>el.addEventListener('scroll',()=>{state.scroll={left:el.scrollLeft,top:el.scrollTop};}));optional('gantt-in',el=>el.addEventListener('click',()=>{state.zoom=Math.min(16,state.zoom*1.5);renderGantt();}));optional('gantt-out',el=>el.addEventListener('click',()=>{state.zoom=Math.max(.5,state.zoom/1.5);renderGantt();}));
  optional('sidebar-toggle',el=>el.addEventListener('click',()=>{state.sidebarOpen=!state.sidebarOpen;renderSidebar();}));for(const key of['agents','tickets'])optional(`side-${key}`,el=>el.addEventListener('click',()=>{state.sidebar=key;renderSidebar();}));optional('search',el=>el.addEventListener('input',(event)=>{state.search=event.target.value;renderSidebar();}));
  optional('play',el=>el.addEventListener('click',togglePlay));optional('follow',el=>el.addEventListener('click',()=>{state.follow=!state.follow;updatePlayback();}));optional('speed',el=>el.addEventListener('change',(event)=>{state.speed=Number(event.target.value);}));optional('cursor',el=>el.addEventListener('input',(event)=>{pause();const range=replayRange();if(range.start===null)return;state.cursor=range.start+(range.end-range.start)*Number(event.target.value)/1000;updatePlayback();}));
  const visibility=()=>{if(document.hidden)pause();};document.addEventListener('visibilitychange',visibility);const onResize=()=>{renderSidebar();if(!mapMode)renderGantt();else state.map?.resize();};window.addEventListener('resize',onResize);
  const resizeObserver=new ResizeObserver(()=>{if(state.destroyed)return;state.map?.resize();bridge.reportSize({width:document.documentElement.clientWidth,height:$('app').getBoundingClientRect().height});});resizeObserver.observe($('app'));
  function cleanup(){if(state.destroyed)return;state.destroyed=true;pause();disposeMap();resizeObserver.disconnect();document.removeEventListener('visibilitychange',visibility);window.removeEventListener('resize',onResize);window.removeEventListener('pagehide',destroy);state.envelope=null;state.model=null;state.replay=null;$('app').replaceChildren();}
  function destroy(){cleanup();return bridge.destroy();}window.addEventListener('pagehide',destroy,{once:true});
  render();if(window.parent===window){tell('noHost');render();}else bridge.connect().then((connected)=>{if(state.destroyed)return;state.connected=connected;render();if(connected)bridge.reportSize({width:document.documentElement.clientWidth,height:$('app').getBoundingClientRect().height});});
}
