package one.rewind.xforce.vehicle_routing.gizmo.test;

import io.quarkus.gizmo.ClassOutput;
import one.rewind.xforce.vehicle_routing.domain.ticket.Ticket;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.optaplanner.core.api.domain.variable.PlanningVariable;
import org.optaplanner.core.impl.domain.common.accessor.MemberAccessor;
import org.optaplanner.core.impl.domain.common.accessor.gizmo.*;
import org.optaplanner.core.impl.util.MutableReference;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.time.LocalDateTime;

import static org.optaplanner.core.impl.domain.common.accessor.gizmo.GizmoMemberAccessorImplementor.defineAccessorFor;

public class GizmoTest {

    @Test
    public void test0() throws NoSuchMethodException, ClassNotFoundException, InvocationTargetException, InstantiationException, IllegalAccessException {

        var gizmoClassLoader = new GizmoClassLoader();

        Method member = Ticket.class.getMethod("getArrivalTime");
        String className = GizmoMemberAccessorFactory.getGeneratedClassName(member);
        MemberAccessor memberAccessor = GizmoMemberAccessorFactory.buildGizmoMemberAccessor(member, PlanningVariable.class, new GizmoClassLoader());

        final MutableReference<byte[]> classBytecodeHolder = new MutableReference<>(null);
        ClassOutput classOutput = (path, byteCode) -> classBytecodeHolder.setValue(byteCode);
        GizmoMemberInfo memberInfo = new GizmoMemberInfo(new GizmoMemberDescriptor(member), PlanningVariable.class);
        defineAccessorFor(className, classOutput, memberInfo);
        byte[] classBytecode = classBytecodeHolder.getValue();

        gizmoClassLoader.storeBytecode(className, classBytecode);

        MemberAccessor generatedAccessor = (MemberAccessor) gizmoClassLoader.loadClass(className)
                .getConstructor().newInstance();

        Assertions.assertNotNull(classBytecode);
        Assertions.assertTrue(classBytecode.length > 0);
        Assertions.assertEquals(memberAccessor.getName(), generatedAccessor.getName());

        Ticket ticket = new Ticket();
        LocalDateTime arrivalTime = LocalDateTime.now();
        ticket.setArrivalTime(arrivalTime);

        Assertions.assertEquals(generatedAccessor.executeGetter(ticket), arrivalTime);

        Assertions.assertTrue(generatedAccessor.supportSetter());

        generatedAccessor.executeSetter(ticket, null);
        Assertions.assertNull(ticket.getArrivalTime());
    }

    @Test
    public void test2() throws NoSuchMethodException {

        var gizmoClassLoader = new GizmoClassLoader();

        Method member = Ticket.class.getMethod("getArrivalTime");
        String className = GizmoMemberAccessorFactory.getGeneratedClassName(member);
        GizmoMemberInfo memberInfo = new GizmoMemberInfo(new GizmoMemberDescriptor(member), PlanningVariable.class);

        MemberAccessor memberAccessor =
                GizmoMemberAccessorFactory.buildGizmoMemberAccessor(member, PlanningVariable.class, new GizmoClassLoader());

        Ticket ticket = new Ticket();
        LocalDateTime arrivalTime = LocalDateTime.now();
        ticket.setArrivalTime(arrivalTime);

        Assertions.assertEquals(memberAccessor.executeGetter(ticket), arrivalTime);
        Assertions.assertTrue(memberAccessor.supportSetter());

        memberAccessor.executeSetter(ticket, null);
        Assertions.assertNull(ticket.getArrivalTime());

        Assertions.assertEquals(memberAccessor.getDeclaringClass(), Ticket.class);
        Assertions.assertEquals(memberAccessor.getGenericType(), member.getGenericReturnType());
        Assertions.assertEquals(memberAccessor.getType(), member.getReturnType());
        Assertions.assertEquals(memberAccessor.getName(), "arrivalTime");
        Assertions.assertEquals(memberAccessor.getSpeedNote(), "Fast access with generated bytecode");
    }
}
